services:
  db:
    image: postgres:13
    restart: always
    environment:
            POSTGRES_DB: ${POSTGRES_DB:-projeto} 
            POSTGRES_USER: ${POSTGRES_USER:-projeto}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projeto}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
