services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: brnoschsaloli
      POSTGRES_PASSWORD: Flamengo81!
      POSTGRES_DB: cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
