apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: brnoschsaloli/nuvemprojeto:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: projeto
            - name: POSTGRES_USER
              value: projeto
            - name: POSTGRES_PASSWORD
              value: projeto
            - name: SECRET_KEY
              value: flamengo
            - name: API_KEY
              value: 127584e87c347080f9081e49dde5cafe
            - name: DB_HOST
              value: db-service #nome do servico do banco de dados
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: web